import ply.lex as lex

#tokens

tokens = [
    'IDENTIFIER','TYPE',
#keywords
    'KEYWORD_ARRAY','KEYWORD_BEGIN','KEYWORD_BREAK','KEYWORD_CASE','KEYWORD_CONST','KEYWORD_CONTINUE',
    'KEYWORD_DO','KEYWORD_DOWNTO','KEYWORD_ELSE','KEYWORD_END',
    'KEYWORD_FILE','KEYWORD_FOR','KEYWORD_FUNCTION','KEYWORD_IF',
    'KEYWORD_IN','KEYWORD_NIL',
    'KEYWORD_OF','KEYWORD_PROCEDURE','KEYWORD_PROGRAM',
    'KEYWORD_RECORD','KEYWORD_REPEAT','KEYWORD_STRING','KEYWORD_THEN','KEYWORD_TO',
    'KEYWORD_TYPE','KEYWORD_UNTIL','KEYWORD_USES','KEYWORD_VAR','KEYWORD_WHILE','KEYWORD_WITH','KEYWORD_XOR',
#literals
    'CONSTANT_INTEGER','CONSTANT_STRING','CONSTANT_REAL','CONSTANT_CHARACTER','CONSTANT_BOOLEAN',
#operators
    'OP_PLUS','OP_MINUS','OP_MULT','OP_DIV','OP_DIV_REAL','OP_MOD',
    'OP_NEQ','OP_GT','OP_LT','OP_GEQ','OP_LEQ',
    'OP_AND','OP_OR','OP_NOT',

    'COMMA','SEMI_COLON','COLON','COLON_EQUAL','LEFT_PARANTHESIS','RIGHT_PARANTHESIS','EQUAL','END_DOT'
    ]

#have to take care of comments
